name: SecretSanta Build And Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    defaults:
      run:
        working-directory: ./SecretSanta/
    runs-on: ubuntu-latest

    steps:
    # checkout the repo
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
          dotnet-version: 5.0.x
    - uses: microsoft/playwright-github-action@v1

    #Getting started with Web Build#
    - name: Get Directory
      run: pwd
      
    - name: npm install
      working-directory: ./SecretSanta/src/SecretSanta.Web/
      run: npm install
      
    - name: npm build
      working-directory: ./SecretSanta/src/SecretSanta.Web/
      run: npm run build:prod

    - name: Restore dependencies Web
      working-directory: ./SecretSanta/src/SecretSanta.Web/
      run: dotnet restore

    # working locally but not in GIT
    # - name: Restore dependencies E2E Test
    #   working-directory: ./SecretSanta/test/SecretSanta.E2E.Tests/
    #   run: dotnet restore

    # - name: Build Web
    #   working-directory: ./SecretSanta/src/SecretSanta.Web/
    #   run: dotnet build --no-restore

    # - name: Build E2E Tests
    #   working-directory: ./SecretSanta/test/SecretSanta.E2E.Tests/
    #   run: dotnet build --no-restore 

    # - name: Test E2E Tests
    #   working-directory: ./SecretSanta/test/SecretSanta.E2E.Tests/
    #   run: dotnet test --no-build --verbosity normal

    #API#
    - name: Restore dependencies API
      working-directory: ./SecretSanta/src/SecretSanta.Api/
      run: dotnet restore

    - name: Restore dependencies API Test
      working-directory: ./SecretSanta/test/SecretSanta.Api.Tests/
      run: dotnet restore

    - name: Build API Tests
      working-directory: ./SecretSanta/test/SecretSanta.Api.Tests/
      run: dotnet build --no-restore 

    - name: Build API
      working-directory: ./SecretSanta/src/SecretSanta.Api/
      run: dotnet build --no-restore

    - name: Test API
      working-directory: ./SecretSanta/test/SecretSanta.Api.Tests/
      run: dotnet test --no-build --verbosity normal
      
    #BUSINESS#

    # - name: Restore dependencies Business
    #   working-directory: ./SecretSanta/src/SecretSanta.Business/
    #   run: dotnet restore

    # - name: Build Business
    #   working-directory: ./SecretSanta/src/SecretSanta.Business/
    #   run: dotnet build --no-restore

    # - name: Restore dependencies Business Tests
    #   working-directory: ./SecretSanta/test/SecretSanta.Business.Tests/
    #   run: dotnet restore

    # - name: Build Business Tests
    #   working-directory: ./SecretSanta/test/SecretSanta.Business.Tests/
    #   run: dotnet build --no-restore 

    # - name: Test Business
    #   working-directory: ./SecretSanta/test/SecretSanta.Business.Tests/
    #   run: dotnet test --no-build --verbosity normal