# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
name: Azure Deployment 

on:
  push:
    branches: [ master ]

jobs:
  build:
    defaults:
      run:
        working-directory: ./SecretSanta/src/SecretSanta.Web
    runs-on: ubuntu-latest

    steps:
    # checkout the repo
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    ###Web###
    - name: npm install
      run: npm install
      
    - name: npm build
      run: npm run build:prod

    - name: Build Web 
      run: dotnet build --no-restore --configuration Release

    - name: dotnet publish Web
      run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/binSecretSanta

    ###Api###  
    
    - name: Build API 
      working-directory: ./SecretSanta/src/SecretSanta.Api/
      run: dotnet build --no-restore --configuration Release

    - name: dotnet publish API
      working-directory: ./SecretSanta/src/SecretSanta.Api/
      run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/binSecretSantaApi

    - name: Deploy web-app
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'Lgarcia29-SecretSanta'
        slot-name: 'Production'
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_E067D0190F7B4CC7909A71F978FC2CB8 }}
        package: ${{env.DOTNET_ROOT}}/binSecretSanta 

    - name: Deploy web-API
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'Lgarcia29-SecretSanta-Api'
        slot-name: 'Production'
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_DB21B47D3BBE407F902F41973654FAA0 }}
        package: ${{env.DOTNET_ROOT}}/binSecretSantaApi